### ISSUE TITLE
当前目录没有写入权限

### ISSUE THREAD

**Issue by SheepYY039** [hisune/emby_pinyin#12]
你好，当我在linux server里执行`composer start`的时候它return `错误：当前目录没有写入权限，请 更换目录 或 尝试以管理员模式运行：/home/yyymx/Downloads/emby_pinyin`. 我试过一下commands都是一样的output，请问我应该怎么运行？谢谢

1. yyymx 用户：`composer start`
2. yyymx 用户：`sudo composer start`
3. root 用户：`composer start`
4. root 用户：`sudo composer start`

**Comment by hisune** [comment]
[0.0.7](https://github.com/hisune/emby_pinyin/releases/tag/0.0.7)版本已修复
