### ISSUE TITLE
音乐专辑和艺术家有办法处理吗

### ISSUE THREAD

**Issue by BenzLeung** [hisune/emby_pinyin#17]
如题。大佬有法子吗？

**Comment by hisune** [comment]
这个我要看看，因为我没有用到emby的音乐专辑，所以之前没关注这一块内容

**Comment by BenzLeung** [comment]
<img width="1268" alt="图片" src="https://user-images.githubusercontent.com/2764768/179141605-3491afc7-de34-4cab-b8fb-70dd38a7d7fc.png">

我用的是jellyfin，通过大佬的工具处理，电影和剧集的排序很完美，就是这个界面没能排序。

**Comment by hisune** [comment]
最新的dev分支自测emby已经支持了，但jellyfin我得测试一下

**Comment by BenzLeung** [comment]
哇大佬好快啊~ 有打包的exe吗？我可以帮忙试试

**Comment by robinletian** [comment]
> 



> 哇大佬好快啊~ 有打包的exe吗？我可以帮忙试试


竟然敢说大佬 好快…

**Comment by hisune** [comment]
> 哇大佬好快啊~ 有打包的exe吗？我可以帮忙试试

那就劳烦帮忙测试下，我这边调试还得重新装个jellyfin

[EmbyPinyin.zip](https://github.com/hisune/emby_pinyin/files/9117627/EmbyPinyin.zip)

**Comment by BenzLeung** [comment]
<img width="983" alt="图片" src="https://user-images.githubusercontent.com/2764768/179150852-78fe7ff7-fa1d-45fd-8387-2d6d3a0984d7.png">

<img width="1269" alt="图片" src="https://user-images.githubusercontent.com/2764768/179151165-9803a0e4-af1d-4f82-9906-0f84d03f6f4e.png">

<img width="1267" alt="图片" src="https://user-images.githubusercontent.com/2764768/179151323-5634fcce-0bfc-4283-90aa-ba3c6aca2895.png">
