### ISSUE TITLE
响应错误，检查您的服务器地址配置

### ISSUE THREAD

**Issue by robinletian** [hisune/emby_pinyin#20]
__                        __               __
.-----.--------.|  |--.--.--.      .-----.|__|.-----.--.--.|__|.-----.
|  -__|        ||  _  |  |  |      |  _  ||  ||     |  |  ||  ||     |
|_____|__|__|__||_____|___  |______|   __||__||__|__|___  ||__||__|__|
by: hisune.com        |_____|______|__|             |_____|
----------------------------------------------------------------------

1) 地址：http://xxxxxx.myqnapcloud.com:8096        API密钥：ca96d170************************
0) 输入新的服务器地址和API密钥

找到 1 个历史服务器，输入编号直接选取(默认为1)，或编号前加减号-删除该配置项，例如：-1
1
地址: http://xxxxxx.myqnapcloud.com:8096, API密钥: ca96d170************************, 开始获取用户信息
当前服务器为：emby，开始获取媒体库信息
获取到 7 个媒体库

-----------------------
1) 首字母
2) 全拼
3) 前置字母
4) 默认
-----------------------
请选择拼音排序方式(默认为1)：
3

是否自动处理所有媒体库？选是将自动处理所有媒体库，选否需要你自行选择处理哪些媒体库。(y/n,默认为n)
y
开始处理 【合集】，选取文字后暂停，回车继续
已跳过：99，已处理：2
开始处理 【电影】，选取文字后暂停，回车继续
响应错误，检查您的服务器地址配置：Connection refused for URI http://xxxxxx.myqnapcloud.com:8096/Users/*****/Items/247452?api_key=ca96d****************
外网登陆。
是什么原因一直连不上呢。。求助大神

**Comment by robinletian** [comment]
症状：
处理到一半报错：响应错误，检查您的服务器地址配置：Connection refused for URI

需要关闭重新打开后才可以继续处理。。

**Comment by hisune** [comment]
正常，网络不稳定导致的，推荐用内网访问

**Comment by robinletian** [comment]
内网OK了。能否安装到nas上并且定期自动执行呢…

谢谢好快的大佬

还有一个小问题，在处理家庭视频和照片的时候，会直接卡自动关闭。。。
![image](https://user-images.githubusercontent.com/58308487/180906391-f5873f86-a8ce-4b76-a511-eb1121fb5983.png)

**Comment by hisune** [comment]
1. 配合readme文档里面的“参数化执行”，无论是windows还是linux都可以用计划任务做到自动执行
2. 卡住的问题有空我做个测试
