### ISSUE TITLE
数字比冒号排名更靠前

### ISSUE THREAD

**Issue by robinletian** [hisune/emby_pinyin#21]
传不上图。。。

选择了3 前置字母

【b巴霍巴利王2：终结】 排在【b巴霍巴利王：开端 】前面

有办法让 【b巴霍巴利王：开端 】在前 【b巴霍巴利王2：终结】 在后吗

ps:目前是手动把【b巴霍巴利王：开端 】改成了【b巴霍巴利王1：开端 】

**Comment by hisune** [comment]
没有办法，数据库中的自然排序就是这样的

**Comment by robinletian** [comment]
![image](https://user-images.githubusercontent.com/58308487/180906849-f4e8d985-92c4-4df1-9e1e-d76d64948077.png)
ce测试了下，windows下  【b巴霍巴利王：开端 】是在 【b巴霍巴利王2：终结】 前面的。

Emm所以数据库的自然排序和windows的排序逻辑是不一样的吗

**Comment by hisune** [comment]
数据库的排序是按ascii进行排序的，：的ascii编号是58，数字2的编号是50，所以是正常的，至于windows是怎么排序的没有了解过
