### ISSUE TITLE
运行的时候出现了乱码

### ISSUE THREAD

**Issue by daiyan299** [hisune/emby_pinyin#24]
在windows 7旗舰版sp1下运行出现乱码
<img width="963" alt="截屏2022-07-30 21 04 59" src="https://user-images.githubusercontent.com/27802101/181915680-b9f929a1-7da3-4e7a-b038-f49a6e0e0575.png">

**Comment by hisune** [comment]
@daiyan299 由于我没有win7的系统环境，可以试下这个版本是否正常：
[EmbyPinyin.zip](https://github.com/hisune/emby_pinyin/files/9230152/EmbyPinyin.zip)

**Comment by daiyan299** [comment]
<img width="602" alt="截屏2022-08-01 22 23 33" src="https://user-images.githubusercontent.com/27802101/182169448-ead4c263-c3e7-425e-a819-560c9dae044c.png">
更改了字体之后就好了，一开始选择的是点阵字体，更换Lucida Console字体重新启动就好了，两个版本都可以使用了
