### ISSUE TITLE
非全中文的标题无法准确识别

### ISSUE THREAD

**Issue by robinletian** [hisune/emby_pinyin#3]
英文或者数字加汉字的混合标题，会按照第一个汉字排序，而不是第一个字符排序。比如x战警是z而不是x排序，，007幽灵党是y而不是0排序

汉字加数字好像是随机排列，比如 侏罗纪公园3，侏罗纪公园，侏罗纪公园2:失落的世界；
蜘蛛侠，蜘蛛侠3，蜘蛛侠2。

其他试了下都很棒，解决了一直以来的排序问题，非常感谢作者！

**Comment by hisune** [comment]
0.0.4版本已修复此问题
