### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by robinletian** [hisune/emby_pinyin#30]
换电脑后新版本闪退，老版本（运行文件名是emby，不是embypinyin）提示PHP Warning:  'vcruntime140.dll' 14.0 is not compatible with this PHP build linked with 14.16 in Unknown on line 0

……

**Comment by robinletian** [comment]
安装Microsoft Visual C++ Redistributable 2019 重启后依旧报错和闪退。

**Comment by hisune** [comment]
> 安装Microsoft Visual C++ Redistributable 2019 重启后依旧报错和闪退。

是否X64和X86的版本都有安装呢？

![image](https://user-images.githubusercontent.com/7941669/201559096-e4d4cd0d-1cfd-46c0-897d-0a1c221bd259.png)

**Comment by robinletian** [comment]
只装了x64,我试试x86

**Comment by robinletian** [comment]
测试安装x86后，正常运行。Please close this issue
