### ISSUE TITLE
通过Webhook无法运行 直接运行可以运行

### ISSUE THREAD

**Issue by GavinIves** [hisune/emby_pinyin#31]
通过webhook会报错 直接跑却可以 out.log里没有日志 err.log日志如下
<img width="868" alt="image" src="https://user-images.githubusercontent.com/38970877/211505601-84aa871f-dcbf-4613-b8da-1fc1509396a2.png">

**Comment by hisune** [comment]
可以看下`emby_pinyin/var/logs/`目录里面的日志

**Comment by GavinIves** [comment]
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/38970877/211703310-037fe129-0f61-462a-9bf0-61664345d462.png">
这里只有上次我手动执行的记录

**Comment by GavinIves** [comment]
已修复 安装好之后需要重启一次
