### ISSUE TITLE
不能找全媒体库

### ISSUE THREAD

**Issue by dickding** [hisune/emby_pinyin#33]
windows版emby服务器，版本4.7.11，服务器有3个媒体库，但emby_pinyin只能找到其中2个。

**Comment by hisune** [comment]
可以确认下未列举出来的媒体库的类型是什么

**Comment by hisune** [comment]
另外就是需要确认你使用的key的对应的这个用户本身是有这个媒体库权限的

**Comment by dickding** [comment]
多谢回复。3个媒体库都是电影，没有列出的媒体库全是iso格式的电影，列出的2个库全是mkv格式的电影，不知是否和这个有关。API KEY没问题的，是用管理员账户创建的，这个管理员是有权访问，删除所有媒体库的。

**Comment by hisune** [comment]
好的，等我有时间测试下这种情况

**Comment by dickding** [comment]
现在搞定了。
不能被找到的这个媒体库，我原先设置为2个用户无权读取，昨天试着设为所有用户都有权读取，这样就能找到这个媒体库了。奇怪的是，我使用的key明明是管理员账户创建的，一直是能读取这个媒体库的。

**Comment by hisune** [comment]
好的，那问题暂时关闭
