### ISSUE TITLE
大佬是否有做docker的兴趣

### ISSUE THREAD

**Issue by daixuan201** [hisune/emby_pinyin#36]
对代码参数比较陌生，但是又希望实现自动化排序，目前我的方法有点麻烦：在windows虚拟机里面，通过按键脚本来定期运行Emby_pinyin.exe，如果能都docker那就太好了

**Comment by hisune** [comment]
等有时间哈

**Comment by daixuan201** [comment]
感谢大佬，exe文件里面可以保存多个emby或jellyfin媒体服务器信息，需要手动依次排序，希望在docker也能加入多个媒体服务器，自动化进行排序

**Comment by hisune** [comment]
[Release 1.0.3](https://github.com/hisune/emby_pinyin/releases/tag/1.0.3)
