### ISSUE TITLE
大神，能不能给EmbyPinyin.exe升级以下几个内容，谢谢

### ISSUE THREAD

**Issue by hyapollo** [hisune/emby_pinyin#37]
1.保存服务器，端口号，密钥，处理的媒体库为INI文件
2.现在操作更新的是SortName字段，能不能加上操作Name字段，功能为：原Name数据+ “ - ” +拼音缩写，或者更加自由的组合方式

看好你，期待您的更新

**Comment by hisune** [comment]
1. 这个的目的是什么呢？现在保存的是json格式文件
2. 这个也应该算一个性化的需求？

**Comment by hyapollo** [comment]
1.目的是能自动化处理，不需要每次手动输入。虽然 有参数可以加，觉的用参数不灵，还是会弹出要求输入
2.能改Name字段，就可以用拼音搜索了，而不需要去的第3方的增强搜索破解。这个SortName只是排序用的吧，没搜索实用
当然能改OriginalTitle也是可以的，能搜索到

**Comment by hisune** [comment]
1. 参数这个正常来说是能获取的，感觉是不是输入了中文横杠—的原因？
2. 这个的确可以加入，如果OriginalTitle可以搜索的话改这个会靠谱点

**Comment by hyapollo** [comment]
不是中文。那我再试试，期待第2项功能

**Comment by hisune** [comment]
[Release 1.0.2](https://github.com/hisune/emby_pinyin/releases/tag/1.0.2)
