### ISSUE TITLE
能不能更简单易用一些，直接安装docker镜像来使用呢？

### ISSUE THREAD

**Issue by daixuan201** [hisune/emby_pinyin#42]
看到了您发布的更新支持了docker非常开心，但是和我想象中的不太一样，并不能拉取docker镜像来安装运行。能否更简单易用一些，类似于jellyfin_pinyin 这个docker的使用模式。

**Comment by huangzlin9** [comment]
+1 用命令行错误

**Comment by huangzlin9** [comment]
+1 用命令行有错误提示

**Comment by dyf991645** [comment]
可以用这个dyf991645/emby-pinyin:latest

环境变量的默认值如下
ENV WEBHOOK_ENABLED=0
ENV CRON_ENABLED=0
ENV CRON_SCHEDULE="0 * * * *"
ENV HOST="http://example:8096"
ENV API_KEY="*****"
ENV SORT_TYPE=1

**Comment by daixuan201** [comment]
> 可以用这个dyf991645/emby-pinyin:latest
> 
> 环境变量的默认值如下 ENV WEBHOOK_ENABLED=0 ENV CRON_ENABLED=0 ENV CRON_SCHEDULE="0 * * * *" ENV HOST="http://example:8096" ENV API_KEY="*****" ENV SORT_TYPE=1

非常感谢！昨天测试是可用的，效果也很好

**Comment by daixuan201** [comment]
> 可以用这个dyf991645/emby-pinyin:latest
> 
> 环境变量的默认值如下 ENV WEBHOOK_ENABLED=0 ENV CRON_ENABLED=0 ENV CRON_SCHEDULE="0 * * * *" ENV HOST="http://example:8096" ENV API_KEY="*****" ENV SORT_TYPE=1

大佬这个docker方便公开吗？我在B站和smzdm发了一篇文章关于拼音排序的

**Comment by dyf991645** [comment]
> > 可以用这个dyf991645/emby-pinyin:latest
> > 环境变量的默认值如下 ENV WEBHOOK_ENABLED=0 ENV CRON_ENABLED=0 ENV CRON_SCHEDULE="0 * * * *" ENV HOST="http://example:8096" ENV API_KEY="*****" ENV SORT_TYPE=1
> 
> 大佬这个docker方便公开吗？我在B站和smzdm发了一篇文章关于拼音排序的

我也是自己有需求，基于这个项目加了个docker。项目开源的，随便用哇。

**Comment by bjzhili** [comment]
> 用这个dyf991645/emby-pinyin:latest>> 环境变量的默认值如下ENV WEBHOOK_ENABLED=0ENV CRON_ENABLED=0ENV CRON_SCHEDULE="0 * * * *"ENV HOST="http://example:8096"ENV API_KEY="*****"ENV排序_类型=1
zhe g

> 可以用这个dyf991645/emby-pinyin:latest
> 
> 环境变量的默认值如下 ENV WEBHOOK_ENABLED=0 ENV CRON_ENABLED=0 ENV CRON_SCHEDULE="0 * * * *" ENV HOST="http://example:8096" ENV API_KEY="*****" ENV SORT_TYPE=1

这个不能支持拼音搜索？只能修改类标题 ，是我设置的不对还是不能更改原标题？
