### ISSUE TITLE
win10计划任务选择每天自动执行加了参数的快捷方式弄不了呢

### ISSUE THREAD

**Issue by 499965994** [hisune/emby_pinyin#43]
计划任务显示有执行成功的，但是没反应，并且没有自动关闭，求大佬解下惑，是必须要用bat才行吗？

**Comment by hisune** [comment]
建议你试用vbs+bat的方式让他后台静默执行，参考脚本如下：
D:\test.vbs
```vbs
Set WshShell = CreateObject("WScript.Shell")
WshShell.Run chr(34) & "D:\emby_pinyin.bat" & Chr(34), 0
Set WshShell = Nothing
```
D:\emby_pinyin.bat
```bat
@echo off
D:\EmbyPinyin.exe -s 1 -t 3 -a n -m 2
```
然后windows添加test.vbs的计划任务即可

**Comment by 499965994** [comment]
哇，谢谢大佬，我去试试

**Comment by 499965994** [comment]
![image](https://github.com/hisune/emby_pinyin/assets/44855261/319e8ea3-169b-4a9f-9670-e239879476cc)
成功了，但是有问题。通过计划启动vbs之后，cli和embyPinyin这两个进程不会自动关闭(如果是手动双击vbs文件启动的话就会自动关闭)，那这样就意味着如果我定时每天都启动一次，那这些进程就会越来越多

**Comment by 499965994** [comment]
经过我的测试，看上去是bat的自动参数或者是var里保存的数据win10计划任务执行vbs后没有读取到，所以虽然这个程序启动了，但是自动化参数没有生效导致的

**Comment by hisune** [comment]
可以试试手动执行bat后是什么效果

**Comment by 499965994** [comment]
手动执行bat也能成功进行自动化然后自动关闭

**Comment by 499965994** [comment]
![image](https://github.com/hisune/emby_pinyin/assets/44855261/693b06c3-5c26-49b5-9658-1eaecfb00be7)
折腾了半天，终于解决了，不需要vbs也不需要bat，可以在计划任务里直接加入参数，但是要填“起始于”的目录，不然读取不到var文件夹应该是
