### ISSUE TITLE
编号：88无效，请重新选取

### ISSUE THREAD

**Issue by robinletian** [hisune/emby_pinyin#5]
例如emby服务器地址是88.myqnapcloud.com，提示  【编号：88无效，请重新选取】。

必须把现有的编号删光才可以重新添加。。。

**Comment by hisune** [comment]
用编号选取的话，直接输入括号前面的编号，而不是域名

**Comment by robinletian** [comment]
> 用编号选取的话，直接输入括号前面的编号，而不是域名

如果要 再添加域名 比如 88.myqnapcloud.com 这种的就不可以了。 会识别成编号而不是域名。

**Comment by hisune** [comment]
> 

添加新域名请先输入0再添加新域名，注意看最后一行编号为的0的描述

**Comment by robinletian** [comment]
OK, 不好意思年纪大了眼神不好哈哈哈。感谢回复
