### ISSUE TITLE
分别用了三个排序方法，就黑客帝国和火星救援，一直排在最前面，请问有解决方法吗？

### ISSUE THREAD

**Issue by JCc101** [hisune/emby_pinyin#51]
如题，下载的是最新win版，试过删除记录和尝试三个排序，这两部电影位置都是不变，请问有解决方法吗？下面为文件排序和emby的显示
![image](https://github.com/hisune/emby_pinyin/assets/81405084/c39e5039-e257-470f-8877-b3558f97ba0b)
![image](https://github.com/hisune/emby_pinyin/assets/81405084/77b3bdbe-290f-45d5-b89d-3c7377fd795a)
![image](https://github.com/hisune/emby_pinyin/assets/81405084/7cc26294-698b-48c2-be47-4df5842f108f)
![image](https://github.com/hisune/emby_pinyin/assets/81405084/db4925b8-d936-4e46-86d5-6895011170e8)
![image](https://github.com/hisune/emby_pinyin/assets/81405084/166f4453-7a79-4ee6-a2e3-dcfcb7c15a19)

![image](https://github.com/hisune/emby_pinyin/assets/81405084/c8856669-82a0-413e-b159-98c37e95a272)
![image](https://github.com/hisune/emby_pinyin/assets/81405084/73788cc5-593e-4404-a2dc-4b46578566f6)

**Comment by hisune** [comment]
看起来像是没有执行到这几部电影的转拼音，可以尝试把媒体库下的所有电影都走执行一遍

**Comment by JCc101** [comment]
> 看起来像是没有执行到这几部电影的转拼音，可以尝试把媒体库下的所有电影都走执行一遍

确实是没有转拼音，删除媒体库啥都没有用，最后手动改了一次生效后就可以了
