### ISSUE TITLE
部分排序不准

### ISSUE THREAD

**Issue by robinletian** [hisune/emby_pinyin#7]
测试了下0.0.4，部分电影名排序有一些问题，如下图红框所示
![微信截图_20220601120557](https://user-images.githubusercontent.com/58308487/171325670-3b321b89-539e-458e-9a72-ebf1e8a87ff2.png)

**Comment by robinletian** [comment]
测试了两个emby服务器 问题复现。
![微信截图_20220601121255](https://user-images.githubusercontent.com/58308487/171326150-ab955f04-995e-49ba-9a97-cbbe9e214726.png)

第一个服务器之前用0.0.3版本整理过， 第二个是第一次使用0.0.4。

麻烦大佬抽时间看一下哈 ：P

**Comment by hisune** [comment]
有啥问题？
有个叫欧维的 -> ygjowd  英格丽向西行 -> yglxxx
明显 ygjowd  要排前面

**Comment by robinletian** [comment]
红色框出来的是我感觉乱入的名字。。

了解了。原来排序是根据每个字的首字母来判断的。 

能否和windows一样按照 同个字一起排序呢

比如图1按照  勇敢的心 - >勇敢者的游戏 - >勇敢者游戏2 这样排序，

![微信截图_20220601122948](https://user-images.githubusercontent.com/58308487/171328254-b79f6535-0a20-47d3-a8e9-d34e2b35d281.png)

**Comment by hisune** [comment]
目前只能按每个字的首字母拼音来排序，不能做到按文字来排序，由于emby只有一个排序字段，如果修改为首字母加汉字的排序方式问题会更大

**Comment by hisune** [comment]
这样不能解决根本问题，因为还存在相同拼音的文字的问题，另外一个不这么做的原因是，如果后面emby能支持排序字段搜索，就可以实现拼音首字母搜索，但这种转全拼的方式后面会有问题，我后面可以出一个版本，可以让用户选择哪种排序方式，以“测试”两个字为例：
1. 拼音首字母：cs
2. 全拼：ceshi
3. 前置首字字母：c测试

第三种方案会比较满足你当前的需求，但后续兼容性会比较差

**Comment by robinletian** [comment]
全拼也会存在问题。例如下面四个电影

A: 爆炸新闻 (2019)
B: 北京遇上西雅图之不二情书 (2016) 
C: 被解救的姜戈 (2012) 
D: 被掩盖的时间 (2016) 

全拼是 
A: bao zha xin wen  (2019)
B: bei jing yu shang xi ya tu zhi bu dong qing shu  (2016) 
C: bei jie jiu de jiang ge  (2012) 
D: bei yan gai de shi jian  (2016) 

首字母：
A: bzxw
B: bjysxyt 
C: bjjdjg
D: byydsj 

测试了下：
Windows/Excel排序：ABCD， 
拼音首字母排序：ACBD
全拼排序：CBDA

搜了下Windows资源管理器文件名排序的规则，发现了这个
https://www.cnblogs.com/wan-deuk/p/15640552.html
不知道有没有帮助

**Comment by robinletian** [comment]
> 这样不能解决根本问题，因为还存在相同拼音的文字的问题，另外一个不这么做的原因是，如果后面emby能支持排序字段搜索，就可以实现拼音首字母搜索，但这种转全拼的方式后面会有问题，我后面可以出一个版本，可以让用户选择哪种排序方式，以“测试”两个字为例：
> 
> 1. 拼音首字母：cs
> 2. 全拼：ceshi
> 3. 前置首字字母：c测试
> 
> 第三种方案会比较满足你当前的需求，但后续兼容性会比较差





可以3+1吗？例如 【c测试cs】 ，既可以排序也可以用首字母搜索。

**Comment by hisune** [comment]
> 全拼也会存在问题。例如下面四个电影
> 
> A: 爆炸新闻 (2019) B: 北京遇上西雅图之不二情书 (2016) C: 被解救的姜戈 (2012) D: 被掩盖的时间 (2016)
> 
> 全拼是 A: bao zha xin wen (2019) B: bei jing yu shang xi ya tu zhi bu dong qing shu (2016) C: bei jie jiu de jiang ge (2012) D: bei yan gai de shi jian (2016)
> 
> 首字母： A: bzxw B: bjysxyt C: bjjdjg D: byydsj
> 
> 测试了下： Windows/Excel排序：ABCD， 拼音首字母排序：ACBD 全拼排序：CBDA
> 
> 搜了下Windows资源管理器文件名排序的规则，发现了这个 https://www.cnblogs.com/wan-deuk/p/15640552.html 不知道有没有帮助

#8  已经实现了所谓的自然排序，在排序表现上和资源管理器一致，到时候使用3的排序方式即可，明天会发个新版本

**Comment by robinletian** [comment]
万分感谢！

**Comment by robinletian** [comment]
0.0.5版，用模式3排序，同一个字可以排在一起了。

ch,sh,zh 和 c,s,z 有办法分开排序吗？ 目前还是随机打乱的。

如：

侏罗纪 - 最后的决斗 - 壮志凌云 -总理之夫 - 扎克施耐德版 ……

**Comment by robinletian** [comment]
系列电影，如果名字后有【冒号加副标题】，第一部会排到最后。

加勒比海盗：黑珍珠... 排在 加勒比海盗5：死无对证后

![微信图片_20220602172211](https://user-images.githubusercontent.com/58308487/171599201-19f67792-358f-4c31-bc8c-7f67494b18db.jpg)
